//
//  ExerciseViewController.h
//  Langenscheidt-Sprachkurs
//
//  Created by Stefan Ueter on 14.01.16.
//  Copyright © 2016 mobilinga. All rights reserved.
//

#import <Foundation/Foundation.h>
@import UIKit;
#import "ExerciseTypes.h"
#import "UserProgressManager.h"


#ifndef ExerciseNavigationController_loaded

#import "ExerciseNavigationController.h"

#endif



typedef NS_ENUM(NSInteger, ExerciseViewControllerVocabularyClass) {
    
    Unknown,
    Word,
    ShortSentence,
    LongSentence
};



typedef NS_ENUM(NSInteger, ExerciseViewControllerLayoutMode) {
    
    ScrollingWithAdjust,
    FullscreenWithAdjust,
    FullscreenWithoutAdjust
};



@interface ExerciseViewController : UIViewController {
    
    BOOL _stopped;
}

@property (nonatomic, strong) NSDictionary* exerciseDict;

//@property (nonatomic, strong) NSDictionary* vocabularyDict;

@property (nonatomic, assign) ExerciseViewControllerLayoutMode layoutMode;

@property (nonatomic, assign) ExerciseNavigationController* exerciseNavigationController;

@property (nonatomic, readonly) BOOL checked;

@property (nonatomic, assign) BOOL canBeChecked;

@property (nonatomic, assign) BOOL mustBeStarted;

@property (nonatomic, assign) BOOL hidesBottomButtonInitially;


+ (ExerciseViewController*) viewControllerForExerciseDictionary:(NSDictionary*) exerciseDict;

+ (NSArray*) autoGeneratedExerciseViewControllersForVocabularyPearl:(Pearl*) pearl;

+ (int32_t) autogeneratedVocabularyExerciseClusterIDRange;

- (NSString*) instruction;

- (void) start;
- (void) stop;
- (void) stopIfNeeded;

- (void) check;

- (void) handleKeyboardDidChangeFrameVisible:(BOOL) visible;

- (BOOL) shouldHandleNextButton;

- (void) handleNextButton;

- (BOOL) shouldHandleContentTap;

- (void) handleContentTap;

- (void) setScore:(NSInteger) score ofMaxScore:(NSInteger) maxScore;

- (void) showBottomButton;

- (void) playCorrectSound;

- (void) playWrongSound;

- (void) scrollBottomToVisible;



#pragma mark - TEMP

+ (NSInteger) numberOfWordsInVocabulary:(Vocabulary*) vocabulary;

@end
